### ISSUE TITLE
Support the token introspection endpoint

### ISSUE THREAD

**Issue by cfman** [axa-group/oauth2-mock-server#160]
## Summary

When testing against my oauth provider, I need the token introspection endpoint.

## Desired solution

When `POST` to the `/introspect` endpoint, return the token info.

Example response

```
{
  "active": true,
  "scope": "read write email",
  "client_id": "J8NFmU4tJVgDxKaJFmXTWvaHO",
  "username": "aaronpk",
  "exp": 1437275311
}
```

## Alternative solutions

N/A

## Additional Context

https://www.oauth.com/oauth2-servers/token-introspection-endpoint/

**Comment by nulltoken** [comment]
@cfman Hey! Can you please tell us about the foreseen implementation?

For instance, how would the `username` and `client_id` fields be valued?

**Comment by cfman** [comment]
Hi @nulltoken , on second thoughts, only the `active` is needed to be returned.
![image](https://user-images.githubusercontent.com/10381489/151183257-b1cacb22-b2d3-44b6-a944-bc9ec79a5736.png)

For `username` and `client_id`, maybe emitting an event like in userInfo endpoint (https://github.com/axa-group/oauth2-mock-server/blob/95398a3f7f8502a1172905815bfd1c71673f40be/src/lib/oauth2-service.ts#L363) for modifying the response object would be good enough.

**Comment by nulltoken** [comment]
@cfman Sounds interesting. Would you feel like contributing this feature?

**Comment by cfman** [comment]
> @cfman Sounds interesting. Would you feel like contributing this feature?

Yes sure, let me try.
