### ISSUE TITLE
Is the sub hardcoded?

### ISSUE THREAD

**Issue by revington** [axa-group/oauth2-mock-server#175]
## Summary

I'm trying to change the `sub` but always returns johndoe

## Steps to Reproduce

Try to change the sub in beforeTokenSigning
Like 
```javascript
 server.service.once('beforeTokenSigning', (token, req) => {   
     token.payload.sub = '123';                                                              
 });                                                           
```

## Expected Behavior

The sub is updated

## Environment

- `oauth2-mock-server` version: _4.3.0_
- Noje.JS version: _16_

## Additional Context

As far as I can see this is actually hardcoded in 4.3.0 because in https://github.com/axa-group/oauth2-mock-server/blob/master/src/lib/oauth2-service.ts#L255-L257 object.assign will always patch the payload with `sub`.
I am right?

**Comment by nulltoken** [comment]
Great catch! Would you fancy to contribute a fix?

**Comment by revington** [comment]
@nulltoken done!

**Comment by nulltoken** [comment]
Closing as per https://github.com/axa-group/oauth2-mock-server/pull/176#discussion_r833635759
