### ISSUE TITLE
How to return a profile to callback

### ISSUE THREAD

**Issue by eric-personal** [axa-group/oauth2-mock-server#188]
How would I return profile object to an OAuth2Strategy callback. 

```
const strategy = new OAuth2Strategy(
  {
    state: true,
    authorizationURL: `${process.env.MOCK_AUTH_SERVER_URL}/authorize`,
    tokenURL: `${process.env.MOCK_AUTH_SERVER_URL}/token`,
    clientID: "xxx",
    clientSecret: "xxx",
    callbackURL: `${process.env.SERVER_URL}/callback`,
    passReqToCallback: true,
  },
  async (accessToken, refershToken, profile, done) => {
    console.log("profile = ", profile);
    if (profile) {
      return done(null, profile);
    }
```
  }
);

I tried updating the tokenEndpointResponse int the beforeResponse emitter but that didn't work.

```
let server = new OAuth2Server();
await server.issuer.keys.generate("RS256");
await server.start(3003, "localhost");
server.service.once("beforeResponse", (tokenEndpointResponse, req) => {
    tokenEndpointResponse.profile = {
      ...tokenEndpointResponse.body,
      id: tokenEndpointResponse.body.id_token,
    };
  });
```

Anyone any idea how I might be able to send back profile,  accessToken and a refershToken ? 
Currently I get back a hash string from profile. example: 0edd82bc-a48c-4a59-8bd6-e79cccc8b2d8

**Comment by eric-personal** [comment]
Thanks @nulltoken OAuth2Strategy is passport. http://www.passportjs.org/packages/passport-oauth2/
I'll try to put something together in the next few days as the project I'm using your mock server on is pretty large.

Basically what I'm trying to test is similar to when someone uses Oauth2 for a login flow. I'd like to fake a profile data which you usually get with when using a login like google oauth. Usually durning the login flow you can do an extra call to get users profile data like email and user id. 
```

router.get(
  "/auth/login",
  passport.authenticate("oauth2", { scope: ["profile"] })
);

strategy.userProfile = function (accessToken, done) {
   // do call to get user profile scope
// return profile data like id or email
};
```

I'd like to bypass this and send back that data via your mocks. 
I though I might be able to do add that mock profile data to one of your event calls before it reaches the callback in an OAuth2 flow. 
That's why I gave the "beforeResponse" event example in my first post. 

One other question I have is when I call req.logOut(); it breaks the below event in your mock server. 

```
  let server = new OAuth2Server();
  await server.issuer.keys.generate("RS256");
  await server.start(3003, "localhost");
  console.log("mock auth server:", server.issuer.url);

  server.service.on("beforeTokenSigning", (token, req) => {
    const credentials = basicAuth(req);
    const clientId = credentials ? credentials.name : req.body.client_id;
    token.payload.aud = clientId;
  });
```
After calling req.logOut();  I try calling my login route again, which before logout would trigger the **beforeTokenSigning** event but after req.logOut();  **beforeTokenSigning** no longer fires.
Does req.logOut(); kill the beforeTokenSigning event in your server ? Or what might be causing this event to stop working after req.logOut(); is called ?

**Comment by thiagobrandam** [comment]
@eric-personal I don't know whether you want to return profile info right away for convenience but classically you would request to another endpoint in the resource server using the access_token provided in the auth grant flow. In that sense, I think you're better off augmenting the response body during `beforeUserInfo` callback

**Comment by nulltoken** [comment]
@poveden Thoughts?

**Comment by poveden** [comment]
OAuth 2 [won't return profile info as part of the access token response](https://www.oauth.com/oauth2-servers/access-tokens/access-token-response/). Passport will fetch the profile on its own _after_ obtaining the token, but _only_ for provider-specific (e.g. Facebook, Twitter) strategies. The generic `OAuth2Strategy` will actually [return an empty object](https://github.com/jaredhanson/passport-oauth2/blob/ee3fe9f17c0f3a90f2d9d938f267e9942b9fba49/lib/strategy.js#L318-L320):

```js
OAuth2Strategy.prototype.userProfile = function(accessToken, done) {
  return done(null, {});
};
```

Probably your best approach would be to extend `OAuth2Strategy` so it fetches the profile from the right place.

**Comment by nulltoken** [comment]
@eric-personal Closing as it looks out of the scope of this library
