### ISSUE TITLE
Add PKCE support

### ISSUE THREAD

**Issue by poveden** [axa-group/oauth2-mock-server#218]
## Summary

Add support for [RFC 7636: Proof Key for Code Exchange](https://oauth.net/2/pkce/) (PKCE).

## Additional Context

PKCE was originally designed to protect the authorization code flow in mobile apps, but its ability to prevent authorization code injection makes it useful for every type of OAuth client, even web apps that use a client secret.

[YouTube: OAuth 2.0 Auth Code Injection Attack in Action](https://www.youtube.com/watch?v=1ot45WwQWJE) (thanks @acasella for the link!)

**Comment by tanettrimas** [comment]
Hi @poveden 

I am considering implementing support for this. Would this be considered a breaking change given that PKCE is required in OAuth 2.1 or should it just be optional to support OAuth 2.0-requests? :)

**Comment by nulltoken** [comment]
:wave: I don't see this as a breaking change.

@poveden Thoughts?

**Comment by poveden** [comment]
Version 7.2.0 has been [published on npm](https://www.npmjs.com/package/oauth2-mock-server). Thanks @tanettrimas!
