### ISSUE TITLE
Add support of Authentication Method "Post"

### ISSUE THREAD

**Issue by kikisaeba** [axa-group/oauth2-mock-server#251]
## Summary

Currently, the Basic authentication is working fine, but some Authentication Server authorized also the "Post" feature (ex: [Auth0](https://auth0.com/docs/secure/tokens/access-tokens/get-access-tokens) ).

The [RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1) mention the support of this method.

The support of the "Post" authentication will help to simulate Authorization Server.

Example: 
```bash
curl --location --request POST 'https://localhost:6666/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials' \
--data-urlencode 'scope=<scope>' \
--data-urlencode 'client_id=<client_id>' \
--data-urlencode 'client_secret=<client_secret>'
```

**Comment by nulltoken** [comment]
@kikisaeba :wave: Thanks for reaching out!

Although there's no specific test covering your use case, the `/token` endpoint  supports form encoded payloads and everything that's posted in the body is made available for introspection and update through the `beforeTokenSigning` customization hook (cf. https://github.com/axa-group/oauth2-mock-server/blob/master/README.md#customization-hooks).

Would this help you enough to proceed further or did I misunderstand your request?

**Comment by kikisaeba** [comment]
@nulltoken Sorry, it was my mistake, the custom function attach to `beforeTokenSigning` verify the `basicAuth` that is not compatible with form encoded payloads.
