### ISSUE TITLE
How to run the CLI?

### ISSUE THREAD

**Issue by redefinered** [axa-group/oauth2-mock-server#28]
in the repo you have an instruction that says "The server can be run from the command line. Run oauth2-mock-server --help for details on its utilization." but there is no info on how to install the CLI.

**Comment by poveden** [comment]
Given that this tool is originally oriented to developers, that message assumes that a user (developer?) is already familiar on invoking npm packages from the CLI.

Certainly, it would help to document that the tool can also be:

- installed globally via `npm install -g oauth2-mock-server`, or
- invoked directly running `npx oauth2-mock-server`.

I'll update the documentation to add these alternative methods.
