### ISSUE TITLE
Support newer version of Node

### ISSUE THREAD

**Issue by alvinsw** [axa-group/oauth2-mock-server#307]
## Summary

When installing the package, npm gives warning EBADENGINE Unsupported engine.
Can we change the supported node version to `>=18.12`?
Since express js supports any Node version `>= 0.10.0`, Is there a reasonable expectation that newer versions of Node will break this mock server? 

## Desired solution

Change the engine property in package.json:
```
"engines": {
  "node": ">=18.12",
  "yarn": "^1.15.2"
},
```

**Comment by nulltoken** [comment]
Thanks for reporting this.

> When installing the package, npm gives warning EBADENGINE Unsupported
engine.

What version of Nodejs are you using?

> Can we change the supported node version to >=18.12?

Unfortunately, we can't blindly commit to support every possible future
version of Nodejs.

However, we will support Nodejs 22 shortly.
Would you be willing to give a hand with this, feel free to open a pull
request (cf.
https://github.com/axa-group/oauth2-mock-server/commit/48e437ff770135d639c835e98ea9e24d86819ff1
)

**Comment by sheinbergon** [comment]
@nulltoken 

I've opened https://github.com/axa-group/oauth2-mock-server/pull/308 per your request.
Looking forward to your approval

**Comment by nulltoken** [comment]
Fixed by #308
