### ISSUE TITLE
Add Management API to set/unset subject

### ISSUE THREAD

**Issue by utamas** [axa-group/oauth2-mock-server#31]
## Summary

I would like to use this tool without the need to write NodeJS and/or create some duplicated code in different projects.

## Desired solution

I would like to have a simple REST API where I can set/unset what username will be set to sub.

## Alternative solutions

?

## Additional Context

Eventually, I would like to bake a docker image from this tool.
My proposed implementation: https://github.com/axa-group/oauth2-mock-server/compare/master...utamas:master.

**Comment by utamas** [comment]
Hi @poveden,
As author to this project could you please share your thoughts on this issue?

**Comment by poveden** [comment]
Hi @utamas,

I've been giving some thought on this topic for a while now, and perhaps it would make sense to send any desired additional fields via HTTP headers, like `X-JWT-Sub: some-value`. Would this work for you?

**Comment by utamas** [comment]
Thank you @poveden for taking the time to consider my proposal.
Let me check if I understand correctly.

Is the proposal that a value (e.g. subject) should be sent when calling the `/token` or `userinfo` endpoints? Wouldn't that mean that a branching logic should be in production code to conditionally set some extra headers during testing?

**Comment by poveden** [comment]
@utamas no, certainly you shouldn't need to have any kind of test logic in production code.

The pattern I had in mind originally for this tool is to test an API that you're developing, and the test code should be able to request tokens as it sees fit. Are you trying some end-to-end approach?

**Comment by utamas** [comment]
@poveden : yes, I would like to use it in E2E tests. I was sure there was a gap in our contexts, thanks for spotting it.

```java
    public void existingUserCanLogin() {
        // GIVEN
        fakeGoogleLoginFor(User);

        //WHEN
        MainPage mainPage = loginUsingGoogle();

        // THEN
        assertThat(mainPage.getModel(), sameJsonAsApproved());
    }
// where
    public void fakeGoogleLoginFor(String requestBody) {
        RequestSpecBuilder requestSpecBuilder = new RequestSpecBuilder()
                .addHeader("Content-type", "application/json")
                .setBaseUri(oauthMockServiceManagementApiUrl)
                .setBody(requestBody)
                .setUrlEncodingEnabled(false);

        Response response = RestAssured.given()
                .spec(requestSpecBuilder.build()).expect()
                .statusCode(SC_OK)
                .when()
                .post(SUBJECT_ENDPOINT);
    }
```
