### ISSUE TITLE
Typescript type definitions

### ISSUE THREAD

**Issue by nulltoken** [axa-group/oauth2-mock-server#35]
## Summary

I'd like to use this from tests written in TypeScript

## Desired solution

TypeScript type defs being part of the published package.

## Additional Context

I can think of three ways to make this happen:
 - Either maintain the types here as a `.d.ts` file
 - Maintain them in DefinitelyTyped repo
 - Port the whole code to TypeScript and let `tsc` generate the type defs

The two first options have great chances to not be always kept in sync
I'd be open to submit a PR to help making the third solution happen.

**Comment by poveden** [comment]
@nulltoken Yes, by all means.
