### ISSUE TITLE
Update README with a link to the npm package

### ISSUE THREAD

**Issue by nulltoken** [axa-group/oauth2-mock-server#4]
https://www.npmjs.com/package/oauth2-mock-server has been published 🎉

Maybe through a service like https://shields.io ?

**Comment by poveden** [comment]
I have a commit already with that. I'll push it soon.

**Comment by poveden** [comment]
There, done: afe144ed7ce346ee377cb70d4b35b4a4e86c475e

**Comment by nulltoken** [comment]
Cool! But why no PR?

**Comment by poveden** [comment]
Well, here's my question: _Why_ a PR? Does really, _everything_, needs to go through a PR? Code I understand, since a PR triggers the CI pipeline and no code changes should skip it, but adding a couple of badges to a README didn't feel like PR-worthy to me. Am I wrong?

**Comment by nulltoken** [comment]
Two thoughts:

 - a PR gives a chance to anybody to engage and discuss

**Comment by nulltoken** [comment]
(Duh. Posted my comment too soon and can't edit it from my phone)

 And

 - Even a README change could contain a typo 😉
