### ISSUE TITLE
npm install fails for version 3.0.0

### ISSUE THREAD

**Issue by tmcgannon** [axa-group/oauth2-mock-server#50]
## Summary

Running npm install on latest version fails.  Install of older version works (`npm install oauth2-mock-server@2.0.0`)

## Steps to Reproduce

1. Using a blank nodejs project, type `npm install oauth2-mock-server`
2. See error below

## Expected Behavior

The npm install completes and modules is installed in my node_modules

## Error Behavior

```bash
➜  npm install oauth2-mock-server

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path /Users/user/Projects/test-oauth/node_modules/oauth2-mock-server/dist/oauth2-mock-server.js
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/user/Projects/test-oauth/node_modules/oauth2-mock-server/dist/oauth2-mock-server.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```

## Environment

- `oauth2-mock-server` version: 3.0.0
- Noje.JS version: v12.18.3
- NPM version: v6.14.8
- Operating System: macOS 10.15.7 (Catalina)

## Additional Context

None

**Comment by poveden** [comment]
@tmcgannon 3.0.1 has just been published with the fix. Thanks for reporting!
