### ISSUE TITLE
server.issuer.keys.add()  issue

### ISSUE THREAD

**Issue by erinwu** [axa-group/oauth2-mock-server#56]
**What**
- cannot add a `use: 'enc'` key

**Line of Code**
- https://github.com/axa-group/oauth2-mock-server/blob/801fd2e9cddda76b2970c1e2a15c8ec6dd3c189a/src/lib/jwk-store.ts#L64

**Suggested Fix**
- `const jwkUse: JWK.Key = { use: 'sig', ...jwk};`

**Comment by nulltoken** [comment]
@erinwu Can you please provide us will a minimal but complete repro case?

**Comment by erinwu** [comment]
@nulltoken  Below is my code.
`const newKey = await server.issuer.keys.add({ // add a RSA-OAEP-256 encrypted key
				kty: 'RSA',
				kid: 'some-key',
				alg: 'RSA-OAEP-256',
				use: 'enc',
				e: 'AQAB',
				n: 'idWPro_...0xKZhnWmjQE8d9xE8e1Z3Ll1LYbw', // eslint-disable-line max-len
			});`

the newKey value should be `JWKBaseKeyObject {
  keystore: JWKStore {},
  length: 2048,
  kty: 'RSA',
  kid: 'some-key',
  use: 'enc',
  alg: 'RSA-OAEP-256'
}` but with the current code, it is `JWKBaseKeyObject {
  keystore: JWKStore {},
  length: 2048,
  kty: 'RSA',
  kid: 'some-key',
  use: 'sig',
  alg: 'RSA-OAEP-256'
}`

**Comment by nulltoken** [comment]
@erinwu Thanks a lot for your answer. Can you please also describe the impact on your own use case this 'sig' normalization causes? What does it prevent you to do? How does this block you in your test process?

**Comment by erinwu** [comment]
@nulltoken  Currently, our project is using `^1.5.1`, and I tried to update it to `^3.0.2` in order to resolve `node-forge` security vulnerability (i.e. `Upgrade node-forge to version 0.10.0 or later`).
During the process, the following error occurs and future debugging found this code changed at https://github.com/axa-group/oauth2-mock-server/compare/v2.0.0...v3.0.0 .

no valid key found in issuer's jwks_uri for key parameters {"alg":"RSA-OAEP-256","use":"enc"}
RPError: no valid key found in issuer's jwks_uri for key parameters {"alg":"RSA-OAEP-256","use":"enc"}

**Comment by nulltoken** [comment]
@erinwu OK. I think I've spotted the issue.

This happened during #48 

```diff
-  async add(jwk) {
-    const jwkUse = { use: 'sig', ...jwk };
+  async add(jwk: JWK.Key): Promise<JWK.Key> {
+    const jwkUse: JWK.Key = { ...jwk, use: 'sig' };
```

I'm not sure how that happened. However, it looks like we didn't have any test to cover this use case.
So a _"let's value `use` with `sig` when unspecified"_ has been turned into _"let's blindly overwrite `use` with `sig`"_. Duh.

Thanks for the report! We'll shortly revert to the previous behavior, add some tests to cover this behavior and publish a patch version.

**Comment by erinwu** [comment]
> @erinwu OK. I think I've spotted the issue.
> 
> This happened during #48
> 
> ```diff
> -  async add(jwk) {
> -    const jwkUse = { use: 'sig', ...jwk };
> +  async add(jwk: JWK.Key): Promise<JWK.Key> {
> +    const jwkUse: JWK.Key = { ...jwk, use: 'sig' };
> ```
> 
> I'm not sure how that happened. However, it looks like we didn't have any test to cover this use case.
> So a _"let's value `use` with `sig` when unspecified"_ has been turned into _"let's blindly overwrite `use` with `sig`"_. Duh.
> 
> Thanks for the report! We'll shortly revert to the previous behavior, add some tests to cover this behavior and publish a patch version.

@nulltoken  Thank you a lot for the help.

**Comment by poveden** [comment]
@erinwu Version 3.0.3 is [live on npm](https://www.npmjs.com/package/oauth2-mock-server). Please confirm that your issue has been fixed. Thanks!

**Comment by erinwu** [comment]
@poveden @nulltoken It works perfectly. Thank you.
