### ISSUE TITLE
Ability to modify authorize redirect url

### ISSUE THREAD

**Issue by markwallsgrove** [axa-group/oauth2-mock-server#58]
## Summary

It is currently not possible to modify the target redirection url used within the authorize handler to a customise the query parameters.

## Desired solution

Emitting a event with the url components to optionally provide the ability to customise the target redirection before [the redirect](https://github.com/axa-group/oauth2-mock-server/blob/master/src/lib/oauth2-service.ts#L313) would be amazing.

## Alternative solutions

Possibility supplying a fixed configuration before executing the server could work, but it wouldn't be as flexible.

## Additional Context

I am attempting to mimic the behavior of Salesforce auth, but the callback query string includes two custom keys (sfdc_community_url, sfdc_community_id) which we require.

**Comment by nulltoken** [comment]
>Emitting a event with the url components to optionally provide the ability to customise the target redirection before the redirect would be amazing.

@markwallsgrove That sounds like a great proposal. Would you feel like contributing it?

**Comment by markwallsgrove** [comment]
@nulltoken sure, no problem.
